# Generated by Django 3.1.2 on 2020-10-12 10:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=300)),
                ('link', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('resource_image', cloudinary.models.CloudinaryField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
